//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb.UserControl {
    
    public partial class UCGenList {
        protected System.Web.UI.WebControls.DropDownList ddlEnable;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.Panel pnlVisible;
        protected System.Web.UI.WebControls.DropDownList ddlGroup;
        protected System.Web.UI.WebControls.DropDownList ddlPM;
        protected System.Web.UI.WebControls.Panel pnlPNVisible;
        protected System.Web.UI.WebControls.CheckBox cbSelectAll;
        protected System.Web.UI.WebControls.GridView GridView2;
        protected System.Web.UI.WebControls.Button btnDownload;
        protected System.Web.UI.WebControls.Panel pnlVisible2;
        protected System.Web.UI.WebControls.CheckBoxList cblGroupList;
        protected System.Web.UI.WebControls.Button btnShowBOM;
        protected System.Web.UI.WebControls.Label lbShowMsg;
        protected System.Web.UI.WebControls.Panel pnlShowBOM;
        protected System.Web.UI.WebControls.CheckBox chkSelect2;
        protected System.Web.UI.WebControls.Button btnDownloadExcel3;
        protected System.Web.UI.WebControls.GridView GridView3;
        protected System.Web.UI.WebControls.Button btnDownloadExcel2;
    }
}
