//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb.UserControl {
    
    public partial class UCResponse {
        protected System.Web.UI.WebControls.Label lbPageState;
        protected System.Web.UI.WebControls.Panel pnlPN;
        protected System.Web.UI.WebControls.DropDownList ddlPNGroup;
        protected System.Web.UI.WebControls.Label lbPNCount;
        protected System.Web.UI.WebControls.Label lbFormdate;
        protected System.Web.UI.WebControls.Label lbPMName;
        protected System.Web.UI.WebControls.GridView GridView1;
    }
}
