//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb.UserControl {
    
    public partial class UCUserList {
        protected System.Web.UI.WebControls.DropDownList ddlEnable;
        protected System.Web.UI.WebControls.GridView GridView1;
    }
}
