//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb.UserControl {
    
    public partial class UploadExcelUserControl {
        protected System.Web.UI.WebControls.FileUpload fpExcelUppload;
        protected System.Web.UI.WebControls.LinkButton btnUpload;
        protected System.Web.UI.WebControls.Label lbErrorMessage;
        protected System.Web.UI.WebControls.Panel pnlSave;
        protected System.Web.UI.WebControls.Label lbSourcerName;
        protected System.Web.UI.WebControls.Label lbFormId;
        protected System.Web.UI.WebControls.Label lbErrMsg;
        protected System.Web.UI.WebControls.Label lbExcelFormId;
        protected System.Web.UI.WebControls.LinkButton lnkSave;
        protected System.Web.UI.WebControls.Label lbSaveErrMsg;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.GridView GridView2;
    }
}
