//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb {
    
    public partial class BomBooking {
        protected System.Web.UI.WebControls.Label lbTitle;
        protected System.Web.UI.WebControls.Panel pnlQuery;
        protected System.Web.UI.WebControls.LinkButton lnkSubmit;
        protected System.Web.UI.WebControls.LinkButton lnkUploadBom;
        protected System.Web.UI.WebControls.LinkButton lnkDownlaodBomTemplate;
        protected System.Web.UI.WebControls.HyperLink hy1;
        protected System.Web.UI.WebControls.Panel pnlUpload1;
        protected System.Web.UI.WebControls.LinkButton lnkBack2;
        protected System.Web.UI.WebControls.Panel pnlCreate;
        protected System.Web.UI.WebControls.LinkButton lnkCreateSave;
        protected System.Web.UI.WebControls.LinkButton lnkCreateBack;
        protected System.Web.UI.WebControls.Panel pnlEdit;
        protected System.Web.UI.WebControls.LinkButton lnkSave;
        protected System.Web.UI.WebControls.LinkButton lnkBack;
        protected System.Web.UI.WebControls.Panel pnlQuery2;
        protected AsusWeb.UserControl.UCBOMList UCBOMList1;
        protected System.Web.UI.WebControls.Panel pnlCreate2;
        protected AsusWeb.UserControl.UCBOM UCBOMCreate1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl pnlEdit2;
        protected AsusWeb.UserControl.UCBOM UCBOM1;
        protected System.Web.UI.WebControls.Panel pnlUpload2;
        protected AsusWeb.UserControl.UploadExcelUserControl UploadExcelUserControl1;
    }
}
