//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb {
    
    public partial class Config {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Panel pnlQuery;
        protected System.Web.UI.WebControls.LinkButton lnkSubmit;
        protected System.Web.UI.WebControls.Panel pnlCreate;
        protected System.Web.UI.WebControls.LinkButton lnkCreateSave;
        protected System.Web.UI.WebControls.LinkButton lnkCreateBack;
        protected System.Web.UI.WebControls.Panel pnlEdit;
        protected System.Web.UI.WebControls.LinkButton lnkSave;
        protected System.Web.UI.WebControls.LinkButton lnkBack;
        protected System.Web.UI.WebControls.Panel pnlQuery2;
        protected AsusWeb.UserControl.UCUserList UCUserList1;
        protected System.Web.UI.WebControls.Panel pnlCreate2;
        protected AsusWeb.UserControl.UCUserEdit UCUserCreate1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl pnlEdit2;
        protected AsusWeb.UserControl.UCUserEdit UCUserEdit1;
        public new AsusWeb.NPI Master {
            get {
                return ((AsusWeb.NPI)(base.Master));
            }
        }
    }
}
