//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb {
    
    public partial class NPI {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.ScriptManager ScriptManager1;
        protected System.Web.UI.UpdateProgress UpdateProgress1;
        protected System.Web.UI.WebControls.Menu Menu1;
        protected System.Web.UI.WebControls.Label lbLoginUser;
        protected System.Web.UI.WebControls.Label lbLoginTime;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
