//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb {
    
    public partial class Query {
        protected System.Web.UI.WebControls.Panel pnlVisible;
        protected System.Web.UI.WebControls.DropDownList ddlSource;
        protected System.Web.UI.WebControls.Button btn1;
        protected System.Web.UI.WebControls.TextBox tbQuery;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.TextBox tbLoginId;
        protected System.Web.UI.WebControls.Button btnUserQuery;
        protected System.Web.UI.WebControls.GridView GridView2;
        protected System.Web.UI.WebControls.TextBox tbPN;
        protected System.Web.UI.WebControls.Button btnQueryBOMSite;
        protected System.Web.UI.WebControls.GridView GridView3;
        protected System.Web.UI.WebControls.GridView GridView4;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.GridView GridView5;
    }
}
