//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusWeb {
    
    public partial class QueryPN {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Panel pnlQuery;
        protected System.Web.UI.WebControls.Panel pnlCreate;
        protected System.Web.UI.WebControls.Panel pnlEdit;
        protected System.Web.UI.WebControls.Panel pnlQuery2;
        protected AsusWeb.UserControl.QueryPNPriceListUserControl QueryPNPriceListUserControl1;
        protected System.Web.UI.WebControls.Panel pnlCreate2;
        protected System.Web.UI.HtmlControls.HtmlGenericControl pnlEdit2;
    }
}
