//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication.UserControl {
    
    public partial class WebUserControl1 {
        protected System.Web.UI.WebControls.PlaceHolder ph1;
    }
}
