//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication {
    
    public partial class WebForm3 {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected TestWebApplication.UserControl.WebUserControl1 WebUserControl1_1;
        protected System.Web.UI.WebControls.TextBox tb1;
    }
}
